version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1/player
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: eclipse-temurin:17-jdk-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./football:/app
    working_dir: /app
    command: sh -c "chmod +x ./mvnw && ./mvnw spring-boot:run"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge